### ISSUE TITLE
Adding 0.000001 still creates an entry which is 0 effectively

### ISSUE THREAD

**Issue by TPH777** [AY2425S1-CS2113-W14-1/tp#157]
![image](https://github.com/user-attachments/assets/a2c85df8-c989-4deb-aceb-32f6ca91cabe)
Handle all amount string to max 2d.p before parsing?

**Comment by wongwh2002** [comment]
edited such that when adding income or spending, will check after rounding to 2dp

**Comment by wongwh2002** [comment]
<img width="841" alt="image" src="https://github.com/user-attachments/assets/6bd5cfcb-6135-468b-accb-813bbcd09198">

**Comment by wongwh2002** [comment]
<img width="519" alt="image" src="https://github.com/user-attachments/assets/83e0b2a2-dc06-4a05-9878-c43dcf3384ba">
