### ISSUE TITLE
When total amount is too large, the amount is capped at "2147483647"

### ISSUE THREAD

**Issue by TPH777** [AY2425S1-CS2113-W14-1/tp#159]
![image](https://github.com/user-attachments/assets/b16d27c8-357f-44e3-a06d-84a31cfd7d70)
![image](https://github.com/user-attachments/assets/fe881c25-0bf8-4071-836b-6453fdaed59f)
However, the entry can still be added, but budget is having float issues also

**Comment by TPH777** [comment]
Similarly, budget is also capped at that value.
![image](https://github.com/user-attachments/assets/e8ec2716-97e2-4027-81b9-e26de037db5f)

**Comment by TPH777** [comment]
![image](https://github.com/user-attachments/assets/51001d23-cd00-4075-9768-e49e9dba54b2)

**Comment by NigelYeoTW** [comment]
as for limitations for amount, would be good to just include inside dg as a limitation of the application, not sure if there is a solution to this

**Comment by wongwh2002** [comment]
yes im changing double for budget, should i create an issue?

**Comment by NigelYeoTW** [comment]
EDIT: track a cap for amount to enter
