### ISSUE TITLE
Missing closing still works

### ISSUE THREAD

**Issue by TPH777** [AY2425S1-CS2113-W14-1/tp#160]
Nested optional arguments:
![image](https://github.com/user-attachments/assets/4e41c104-c38c-4f75-9501-bb7fe429fcb2)
![image](https://github.com/user-attachments/assets/111198c0-507a-42e3-a8ef-caee30b29f4e)

**Comment by TPH777** [comment]
Empty string password

**Comment by NigelYeoTW** [comment]
check closing tag (check for size after padding)
