### ISSUE TITLE
Unable to save files

### ISSUE THREAD

**Issue by wongwh2002** [AY2425S1-CS2113-W14-1/tp#163]
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/8f920dba-dbe2-4e0e-86c7-a58fd491b4b1">

**Comment by wongwh2002** [comment]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/36f39086-fe7b-4949-be45-88deb80d2f8e">

**Comment by wongwh2002** [comment]
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/cae92a07-1a50-4fad-be87-9c691cb8c89a">
<img width="830" alt="image" src="https://github.com/user-attachments/assets/04de457d-f9fd-4eae-9677-8a9935c68656">
<img width="330" alt="image" src="https://github.com/user-attachments/assets/6fb3988e-080c-4367-bb43-16de8769441f">

**Comment by wongwh2002** [comment]
hmm i cant recreate the bug anymore, I initially thought it was because i "add spending 0.005 mcds"
but reruning the problem removes the bug?? did anyone get this error

**Comment by wongwh2002** [comment]
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/dd1d292d-5282-40b0-9812-518434790580">
i get it randomly, might be issue with intellij or mac??

**Comment by wongwh2002** [comment]
i realised my mac really did not have space, which is technically not a bug
did anyone face this before? else ill close issue

**Comment by NigelYeoTW** [comment]
developer specific issue
