### ISSUE TITLE
Possible improvements for code quality

### ISSUE THREAD

**Issue by TPH777** [AY2425S1-CS2113-W14-1/tp#178]
1. Replace all `\t` with `TAB` constant
2. Inconsistent naming of method arguments, e.g. `arrList` and `list`, `optionalString` and `optionalArguments`
3. Inconsistent naming of attributes, e.g. For incomes/spendings: `category`, `type`, `field` and `list` across docs and code.
4. Inconsistent naming of test E.g. expected output is `throwWiagiException` or the message in the exception itself.
5. Remove including command format message in exceptions if the user command is in the correct format but of invalid input
6. Extract `LocalDate.now()` to a constant or change `VALID_TEST_DATE` name so to be used in the main program also.
7. Extract `Math.round(doubleToFormat * 100.0) / 100.0` to a method as it is used alot in the program.
8. Add Junit test for list total overflow in `add`, `edit` and `recurrence`

**Comment by wongwh2002** [comment]
spendinglist class, setDialyBudget, to use format in utils instead (point 7)

**Comment by NigelYeoTW** [comment]
all members edited and cleaned code
