### ISSUE TITLE
[PE-D][Tester A] Specificity of Error Message for inputting budget

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W14-1/tp#201]
![image.png](https://raw.githubusercontent.com/CheeKiangg/ped/main/files/bf415999-bc9d-4a61-8b74-40bb31d04180.png)

Error messages could be more specific in telling user that numbers inputted cannot have white space(s) between them. Alternatively, you could try to allow for input that contain numbers and white spaces in your code base, allowing more flexibility for user input

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: CheeKiangg/ped#2

**Comment by wongwh2002** [comment]
specify in UG, inputs for amount must be a valid number, give examples on valid and invalid input

**Comment by wongwh2002** [comment]
done for UG in creation of new user and set budget
