### ISSUE TITLE
[PE-D][Tester A] Unnecessarily complicated commands format for add spending

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W14-1/tp#204]
![image.png](https://raw.githubusercontent.com/CheeKiangg/ped/main/files/9717b497-ea80-483e-8805-cf60c6e9c0eb.png)

input formats are expected to be optimized to get things done quickly. There could be excessive use of hard to type special characters.

`add spending 21.50 telgram premium /2024-10-20/ *personal expense* ~monthly~` could be changed to
`add spending 21.50 telgram premium /2024-10-20 *personal expense ~monthly`

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: CheeKiangg/ped#3

**Comment by wongwh2002** [comment]
invalid issue, supposed to be fast typist, issue out of user scope.
