### ISSUE TITLE
[PE-D][Tester A] Incorrect Listing of Tags (part ii)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W14-1/tp#219]
![image.png](https://raw.githubusercontent.com/CheeKiangg/ped/main/files/1ed3c23e-29ad-493e-bcaf-0f69ecb1c3a0.png)

when searching for tag, I feel that the tag be case-insensitive, as this will make searching for expenses more convenient from the user perspective 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: CheeKiangg/ped#8

**Comment by wongwh2002** [comment]
.equalsignorecase()
when listing tags
