### ISSUE TITLE
Amount accepts "f" and "d"  at the back

### ISSUE THREAD

**Issue by wx-03** [AY2425S1-CS2113-W14-1/tp#247]
![image](https://github.com/user-attachments/assets/eff9d8fc-a0b0-4f7e-af7f-920f22c0abe7)

**Comment by wongwh2002** [comment]
![{3BE9B710-2428-4534-BE91-875CE8575E6B}](https://github.com/user-attachments/assets/b8b702d0-94a1-4dd6-ac16-e7f9c4e34b09)
solved

**Comment by wongwh2002** [comment]
![{ADA248A7-733A-47F1-96B8-85281B17A263}](https://github.com/user-attachments/assets/ab9b025d-18cc-451e-b000-6a1b77f8870e)
ok
