### ISSUE TITLE
Wrong line number for file corruption

### ISSUE THREAD

**Issue by wx-03** [AY2425S1-CS2113-W14-1/tp#249]
![image](https://github.com/user-attachments/assets/314a38f7-0f9d-4071-9c84-9372ec4f5d1d)

**Comment by wx-03** [comment]
Should +1 ?

**Comment by wongwh2002** [comment]
what is the expected output

**Comment by wongwh2002** [comment]
![{13617E88-C7ED-4FDD-A943-5B069BBDA833}](https://github.com/user-attachments/assets/b9b514d5-df26-43c4-9a33-043ed35a56b8)
ok
