### ISSUE TITLE
Users unable to use '/', '*', '~' in description

### ISSUE THREAD

**Issue by NigelYeoTW** [AY2425S1-CS2113-W14-1/tp#82]
Only check substring after description for add function and parse the date, recurrence and tag from there.

![Screenshot 2024-10-26 150219](https://github.com/user-attachments/assets/8bed70fb-ab0b-4e6a-a315-1acf2e949105)

**Comment by TPH777** [comment]
Can consider adding escape character for this

**Comment by wongwh2002** [comment]
what do you mean by escape character

**Comment by wongwh2002** [comment]
my plan here was to add a big exclaimation somewhere saying they cant use it (in DG and UG)

**Comment by NigelYeoTW** [comment]
Resolved to user limitations in input, added to the UG
